feat: deploy-oracle-PT-Dec-maturity
AngleProtocol/borrow-contracts pull request #257
Opened 2024-06-10 14:35 UTC by GuillaumeNervoXS

2024-06-14 12:30 UTC, 0xtekgrinder approved these changes
Maybe remove broadcast folder otherwise looks good

2024-06-14 12:30 UTC, 0xtekgrinder commented on test/foundry/oracles/pendle/MorphoFeedPTezETHDec24.t.sol
> +    // }
why has this been commented ?

2024-06-17 16:44 UTC, 0xtekgrinder requested changes
Just a file to remove otherwise looks good to me

2024-06-17 16:44 UTC, 0xtekgrinder commented on contracts/oracle/FeedPTForSY.sol
can remove this contract

2024-06-17 16:53 UTC, GuillaumeNervoXS commented on contracts/oracle/FeedPTForSY.sol
I want to keep it as it was one of the issue not being able to price in the SY token, not used because current PT tokens can be priced in the asset (ETH) but could be useful

2024-06-18 07:49 UTC, 0xtekgrinder approved these changes

2024-06-18 15:03 UTC, merged